### ISSUE TITLE
Needed to require 'redcarpet'?

### ISSUE THREAD

**Issue by golmansax** [zooppa/administrate-field-simple_markdown#1]
Hi, I had to add `require 'redcarpet'` to my `config/application.rb`, or else I got an error on server boot: `~/.rvm/gems/ruby-2.4.0/gems/redcarpet-3.4.0/lib/redcarpet/render_strip.rb:5:in '<module:Render>': uninitialized constant Redcarpet::Render::Base (NameError)`

Any ideas to what's going on?  Thanks.

**Comment by michelegera** [comment]
Hey @golmansax, sorry for the super late reply but this slipped off my radar for a while 😅
I’ve just [released v0.1.0](https://github.com/zooppa/administrate-field-simple_markdown/releases/tag/v0.1.0) that should fix this particular issue.

**Comment by golmansax** [comment]
@michelegera I upgraded the package and it works great.  Thanks!
